/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.movimiento;

import javax.swing.JFrame;
import java.util.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import modelo.movimiento.mReservaCliente;
import modelo.mantenimiento.*;
import controlador.*;
import principal.*;

/**
 *
 * @author Ignacio
 */
public class formReservaCliente extends javax.swing.JFrame {

    
    mReservaCliente mrc;
    reservas r;
    mVehiculo mv;
    modificar m;
    permisos p;
    
    private Date factual = new Date();
    private SimpleDateFormat s = new SimpleDateFormat("dd / MM / YYYY");
    
    private int d = 0;
    private int X = 0, Y = 0, Z = 0;
    private int I = 0, J = 0, K = 0;
    
    public static String linea_A;
    
    /**
     * Creates new form formReservaCliente
     */
    public formReservaCliente() {
        
        initComponents();
        setTitle("Reserva Cliente | RentCar System");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        
        try{
            dateSalida.setMinSelectableDate(factual);
            dateEntrada.setMinSelectableDate(factual);
            getFechaReserva.setText(String.valueOf(s.format(factual)));
        }catch(NullPointerException n)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOferta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        getFechaReserva = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        getDiasReservas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        getPrecioRecerva = new javax.swing.JLabel();
        dateSalida = new com.toedter.calendar.JDateChooser();
        dateEntrada = new com.toedter.calendar.JDateChooser();
        txtCliente = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIDReserva = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        estados = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        Vehiculo = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        getMarca = new javax.swing.JLabel();
        getGama = new javax.swing.JLabel();
        getDesc = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        getEstado = new javax.swing.JLabel();
        Cliente = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        getFullname = new javax.swing.JLabel();
        getDirec = new javax.swing.JLabel();
        getPhone = new javax.swing.JLabel();
        Oferta = new javax.swing.JLayeredPane();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        getOdesc = new javax.swing.JLabel();
        getPrecio = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/important-day.png"))); // NOI18N
        jLabel1.setText("Reserva Cliente");

        msg.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Matricula");

        txtMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaFocusLost(evt);
            }
        });
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID Cliente");

        txtOferta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOferta.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Oferta");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fecha Reserva");

        getFechaReserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getFechaReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getFechaReserva.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Fecha Salida");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fecha Entrada");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Observacion");

        txtObservacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Dias Reserva");

        getDiasReservas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getDiasReservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getDiasReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Total Reserva");

        getPrecioRecerva.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getPrecioRecerva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getPrecioRecerva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        dateSalida.setFocusTraversalPolicyProvider(true);
        dateSalida.setFocusable(false);
        dateSalida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateSalida.setNextFocusableComponent(dateEntrada);
        dateSalida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateSalidaPropertyChange(evt);
            }
        });

        dateEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateEntradaPropertyChange(evt);
            }
        });

        try {
            txtCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("ID Reserva");

        txtIDReserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIDReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDReservaKeyPressed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/floppy-disk.png"))); // NOI18N
        btnGuardar.setText(" Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forward.png"))); // NOI18N
        btnCerrar.setText(" Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/floppy-remove.png"))); // NOI18N
        btnEliminar.setText(" Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtOferta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(getFechaReserva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtObservacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(getDiasReservas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(getPrecioRecerva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dateSalida, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dateEntrada, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtIDReserva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(getDiasReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(getPrecioRecerva, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(getFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(txtIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getPrecioRecerva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getDiasReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        estados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        estados.setForeground(new java.awt.Color(255, 0, 0));

        Vehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Vehiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Marca:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Gama:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Descripcion:");

        getMarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getMarca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        getGama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getGama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        getDesc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getDesc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Estado:");

        getEstado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getEstado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        Vehiculo.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(getMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(getGama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(getDesc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Vehiculo.setLayer(getEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VehiculoLayout = new javax.swing.GroupLayout(Vehiculo);
        Vehiculo.setLayout(VehiculoLayout);
        VehiculoLayout.setHorizontalGroup(
            VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getMarca))
                    .addGroup(VehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getGama))
                    .addGroup(VehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getDesc))
                    .addGroup(VehiculoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(getEstado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VehiculoLayout.setVerticalGroup(
            VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(getMarca))
                .addGap(18, 18, 18)
                .addGroup(VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(getGama))
                .addGap(18, 18, 18)
                .addGroup(VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(getDesc))
                .addGap(18, 18, 18)
                .addGroup(VehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(getEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Nombre:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Direccion:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Telefono:");

        getFullname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getFullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        getDirec.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getDirec.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        getPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        Cliente.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Cliente.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Cliente.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Cliente.setLayer(getFullname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Cliente.setLayer(getDirec, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Cliente.setLayer(getPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente);
        Cliente.setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getFullname))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getDirec))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getPhone)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(getFullname))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(getDirec))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(getPhone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Oferta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Oferta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setText("Descripcion:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setText("Precio:");

        getOdesc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getOdesc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        getPrecio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        Oferta.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Oferta.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Oferta.setLayer(getOdesc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Oferta.setLayer(getPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout OfertaLayout = new javax.swing.GroupLayout(Oferta);
        Oferta.setLayout(OfertaLayout);
        OfertaLayout.setHorizontalGroup(
            OfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OfertaLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getOdesc))
                    .addGroup(OfertaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getPrecio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OfertaLayout.setVerticalGroup(
            OfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(getOdesc))
                .addGap(18, 18, 18)
                .addGroup(OfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(getPrecio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setLayer(Vehiculo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Cliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(Oferta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vehiculo)
                    .addComponent(Cliente)
                    .addComponent(Oferta))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Oferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel15.setText("Norificaciones:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLayeredPane3))
                    .addComponent(estados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        mrc = new mReservaCliente();
        if(verify())
        {
            linea_A = txtIDReserva.getText()+"_"+txtMatricula.getText()+"_"+txtCliente.getText()+"_"
                    +txtOferta.getText()+"_"+getFechaReserva.getText()+"_"
                    +s.format(dateSalida.getDate())+"_"+s.format(dateEntrada.getDate())
                    +"_"+txtObservacion.getText()+"_"+getDiasReservas.getText()+"_"
                    +getPrecioRecerva.getText();
            
            if(changeStatus())
            {
                mrc.add(linea_A);
                clear();
                msg.setForeground(Color.blue);
                msg.setText("Datos Guardados");
            }else{
                msg.setForeground(Color.red);
                msg.setText("Datos No guardados");
            }
            
            dateSalida.setCalendar(null);
            dateEntrada.setCalendar(null);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaFocusLost
        // TODO add your handling code here:
        if(!txtMatricula.getText().equals("")){
            r = new reservas();
            if(!r.model_C(txtMatricula.getText())){
                // mensaje;
                txtOferta.setText("No tiene");
            }else{
                estados.setText("");
            }
        }
    }//GEN-LAST:event_txtMatriculaFocusLost

    private void txtMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            r = new reservas();
            if(!r.model_A(txtMatricula.getText()))
            {
                // mensaje;
            }else{
                txtMatricula.transferFocus();
            }
            
        }
    }//GEN-LAST:event_txtMatriculaKeyPressed

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            r = new reservas();
            if(!r.model_B(txtCliente.getText()))
            {
                estados.setText("Cliente no Registrado");
            }else{
                estados.setText("");
                dateSalida.setFocusable(true);
            }
        }
    }//GEN-LAST:event_txtClienteKeyPressed

    private void dateEntradaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateEntradaPropertyChange
        // TODO add your handling code here:
        
        try{
          if(!getGama.getText().equals(""))
            {
                //Captura: Dia, Mes, Año de la fecha de salida
                X = dateSalida.getCalendar().get(Calendar.DAY_OF_MONTH);
                Y = dateSalida.getCalendar().get(Calendar.MONTH);
                Z = dateSalida.getCalendar().get(Calendar.YEAR);
                //Captura: Dia, Mes, Año de la fecha de entrada
                I = dateEntrada.getCalendar().get(Calendar.DAY_OF_MONTH);
                J = dateEntrada.getCalendar().get(Calendar.MONTH);
                K = dateEntrada.getCalendar().get(Calendar.YEAR);
                //Comprovando que la fecha de entrada no sea menor que la salida
                if(K >= Z){
                    if(J >= Y){
                        if(I > (X+1)){
                            for(int i = X; i<I;i++)
                            {
                                d++;
                            }
                            getDiasReservas.setText(String.valueOf(d)+" Dias");
                            //Verifico si la el tiempo de Reserva esta Vacio
                            if(!getDiasReservas.getText().equals("")){
                                //Objeto para utilizar el controlador utilizado para adquirir la 
                                //informacion del Vehiculo, Usuario y la Oferta.
                                r = new reservas();
                                //Almaceno el precio en una variable Double
                                Double Precio = ((r.getPrecio(txtMatricula.getText()))*d);
                                //estados.setText(String.valueOf(Precio));
                                //Si la vista del Precio no esta en Blanco Ejecuto la oferta
                                if(!getPrecio.getText().equals("")){
                                    //Almaceno el porciento a descontar en una vareable Double.
                                    double D = ((Double.valueOf(getPrecio.getText())*Precio)/100);
                                    //Le doy salida al resultado del calculo en el label getPrecioReserva
                                    getPrecioRecerva.setText("RD$ "+String.valueOf( (Precio-D) ));
                                    //Si la vista del Precio si esta en Blanco no ejecuto la oferta
                                }else{
                                    //Le doy salida al resultado del calculo en el label getPrecioReserva
                                    getPrecioRecerva.setText("RD$ "+String.valueOf(Precio* (double) d));
                                }
                            }
                            d = 0;

                        }else{
                            estados.setText("La fecha de Entrada no puede ser menor que la de Salida");
                        }
                    }else{
                        estados.setText("La fecha de Entrada no puede ser menor que la de Salida");
                    }
                }else{
                    estados.setText("La fecha de Entrada no puede ser menor que la de Salida");
                }
            }  
        }catch(NullPointerException n)
        {
            
        }
    }//GEN-LAST:event_dateEntradaPropertyChange

    private void dateSalidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateSalidaPropertyChange
        // TODO add your handling code here:
        //Captura: Dia, Mes, Año de la fecha de salida
        try{
            dateEntrada.setMinSelectableDate(dateSalida.getDate());
        }catch(NullPointerException n)
        {
            
        }
    }//GEN-LAST:event_dateSalidaPropertyChange

    private void txtIDReservaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDReservaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            mrc = new mReservaCliente();
            if(mrc.verify(txtIDReserva.getText()))
            {
                msg.setText("Registrado");
                btnEliminar.setEnabled(true);
                security(0);
                estados.setText(linea_A);
            }else{
                msg.setText("Creando");
                security(1);
                clear();
                dateSalida.setCalendar(null);
                dateEntrada.setCalendar(null);
            }
            txtIDReserva.transferFocus();
        }
    }//GEN-LAST:event_txtIDReservaKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        p = new permisos(linea_A, txtMatricula.getText());
        //clear();
        //dateSalida.setCalendar(null);
        //dateEntrada.setCalendar(null);
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    boolean verify()
    {
        boolean its = true;
        if(txtIDReserva.getText().equals(""))
        {
            txtIDReserva.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe Ingresar el ID", "Campo Obligatorio", JOptionPane.ERROR_MESSAGE);
            txtIDReserva.setBackground(Color.white);
            its = false;
        }else if(txtMatricula.getText().equals(""))
        {
            txtMatricula.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe Ingresar la Matricula", "Campo Obligatorio", JOptionPane.ERROR_MESSAGE);
            txtMatricula.setBackground(Color.white);
            its = false;
        }else if(txtCliente.getText().equals(""))
        {
            txtCliente.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe Ingresar la Cedula del Cliente", "Campo Obligatorio", JOptionPane.ERROR_MESSAGE);
            txtCliente.setBackground(Color.white);
            its = false;
        }else if(dateSalida.getCalendar().get(Calendar.DATE) == 0)
        {
            dateSalida.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe Ingresar la fecha de Salida", "Campo Obligatorio", JOptionPane.ERROR_MESSAGE);
            dateSalida.setBackground(Color.white);
            its = false;
        }else if(dateEntrada.getCalendar().get(Calendar.DATE) == 0)
        {
            dateSalida.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Debe Ingresar la fecha de Entrada", "Campo Obligatorio", JOptionPane.ERROR_MESSAGE);
            dateSalida.setBackground(Color.white);
            its = false;
        }else if(txtObservacion.getText().equals(""))
        {
            txtObservacion.setText("Buen Estado");
        }
        return its;
    }

    void clear()
    {
        //txtIDReserva.setText("");
        txtMatricula.setText("");
        txtCliente.setText("");
        txtOferta.setText("");
        getDiasReservas.setText("");
        getPrecioRecerva.setText("");
        txtObservacion.setText("");
        
        getMarca.setText("");
        getGama.setText("");
        getDesc.setText("");
        getEstado.setText("");
        
        getFullname.setText("");
        getDirec.setText("");
        getPhone.setText("");
        
        getOdesc.setText("");
        getPrecio.setText("");
        linea_A = "";
    }
    
    boolean changeStatus()
    {
        boolean its = false;
        mv = new mVehiculo();
            m = new modificar(mv.path);
            if(m.change_status(mv.verify_toStatus(txtMatricula.getText()),0))
            {
                m.editar();
                if(m.reenombrar())
                {
                    //estados.setText("Estado del Vehiculo Cambiado");
                    its = true;
                }
            }
        return its;
    }
    
    void security(int i)
    {
        if(i == 0)
        {
            //txtIDReserva.setEnabled(false);
            txtMatricula.setEnabled(false);
            txtCliente.setEnabled(false);
            txtOferta.setEnabled(false);
            dateSalida.setEnabled(false);
            dateEntrada.setEnabled(false);
            getDiasReservas.setEnabled(false);
            getPrecioRecerva.setEnabled(false);
            txtObservacion.setEnabled(false);
        }else if(i == 1)
        {
            //txtIDReserva.setEnabled(true);
            txtMatricula.setEnabled(true);
            txtCliente.setEnabled(true);
            txtOferta.setEnabled(true);
            dateSalida.setEnabled(true);
            dateEntrada.setEnabled(true);
            getDiasReservas.setEnabled(true);
            getPrecioRecerva.setEnabled(true);
            txtObservacion.setEnabled(true);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Cliente;
    private javax.swing.JLayeredPane Oferta;
    private javax.swing.JLayeredPane Vehiculo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    public static com.toedter.calendar.JDateChooser dateEntrada;
    public static com.toedter.calendar.JDateChooser dateSalida;
    public static javax.swing.JLabel estados;
    public static javax.swing.JLabel getDesc;
    public static javax.swing.JLabel getDiasReservas;
    public static javax.swing.JLabel getDirec;
    private javax.swing.JLabel getEstado;
    private javax.swing.JLabel getFechaReserva;
    public static javax.swing.JLabel getFullname;
    public static javax.swing.JLabel getGama;
    public static javax.swing.JLabel getMarca;
    public static javax.swing.JLabel getOdesc;
    public static javax.swing.JLabel getPhone;
    public static javax.swing.JLabel getPrecio;
    public static javax.swing.JLabel getPrecioRecerva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel msg;
    public static javax.swing.JFormattedTextField txtCliente;
    private javax.swing.JTextField txtIDReserva;
    public static javax.swing.JTextField txtMatricula;
    public static javax.swing.JTextField txtObservacion;
    public static javax.swing.JTextField txtOferta;
    // End of variables declaration//GEN-END:variables
}
